### ISSUE TITLE
local_variables sometimes lies

### ISSUE THREAD

**Issue by hx** [denofevil/debase#13]
I use the IntelliJ/RubyMine debugger, which occasionally trips on [this line](https://github.com/denofevil/debase/blob/master/lib/debase/context.rb#L7). The gist is here:

```ruby
locals = eval("local_variables", binding)
locals.each {|local| result[local.to_s] = eval(local.to_s, binding)}
```

The `local_variables` method is reporting some variable names (in my case, `m`), which, when evaled, raises uncaught errors that crash the debugger.

I'm thinking, at the very least:

```ruby
locals.each {|local| result[local.to_s] = eval(local.to_s, binding) rescue :ghost}
```

Then, in our debuggers' lists of locals, it'd be clear that the variable *did* or *should* exist, but doesn't. Also, we could still debug stuff.

Thoughts, anybody?

**Comment by hx** [comment]
@os97673 I just saw this. It's on my todo list now ;)

**Comment by os97673** [comment]
I believe the problem has been fixed, feel free to reopen if it is not.
