### ISSUE TITLE
Debase version 0.2.2-beta7 causes stops at random code locations

### ISSUE THREAD

**Issue by mbasset** [denofevil/debase#26]
Not sure if this is a Debase issue but while debugging with the latest version (0.2.2-beta7) which is installed by on a rubymine installation when using the debugger I have issues with breaking at random spots. This only happens when using breakpoints (in any part of code) with rails. The system will randomly stop at lines of code that do not have breakpoints that appear to be deep within the rails gems. I have downgraded to 0.2.2-beta6 for now and that seems to have made the issue better but not sure what has changed.

Info:

Rubymine 2016.1
Debase 0.2.2-beta7
Ruby 2.3.1p112
debase-ruby_core_source 0.9.0
ruby-debug-ide 0.6.1.beta2

**Comment by hyjk2000** [comment]
There's a bug report on the official issue tracker of RubyMine: [RUBY-17990](https://youtrack.jetbrains.com/issue/RUBY-17990)
