### ISSUE TITLE
Build Fails MYS2

### ISSUE THREAD

**Issue by cfis** [denofevil/debase#32]
debase-0.2.2.beta9 no longer builds on msys2 on Windows.

Error:

x86_64-w64-mingw32-gcc -shared  -o attach.so attach.o -L. -L/C/msys64/local/ruby/lib -L. -Lc:/msys64/local/lib -Wl,--enable-auto-image-base,--enable-auto-import attach-x64-mingw32.def    -lx64-msvcrt-ruby230
 -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi
Cannot export Init_attach: symbol not defined

attach-x64-mingw32.def exists and defines  Init_attach, but attach.c does not define this method. Thus the shared library cannot be built and the gem can't be installed. 

This is new in beta9, previous versions built correctly.

gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32

**Comment by denofevil** [comment]
Should be fixed with  49845dd, can you try latest master?

**Comment by cfis** [comment]
Yes that fixes - thanks!
