### ISSUE TITLE
VC Compilation Broken

### ISSUE THREAD

**Issue by cfis** [denofevil/debase#39]
The latest stable release of debase compiles on Visual Studio, but the betas do not.  The issue is this code:

static void
__attribute__ ((noinline))
__func_to_set_breakpoint_at()
{
  asm("");
}

asm is not supported on 64 bits on Visual Studio.  It would have to be something like this:

static void
__declspec(noinline)
__func_to_set_breakpoint_at()
{
}

Not sure that accomplishes what needs to be done, but at least it compiles.

**Comment by denofevil** [comment]
@equivalence1

**Comment by denofevil** [comment]
@cfis I've merged the fix that should resolve this, can you check whether it works for you?

**Comment by cfis** [comment]
Sorry, yes it did.
