### ISSUE TITLE
Problem with Rails 5 + Ruby 2.5

### ISSUE THREAD

**Issue by wellington1993** [denofevil/debase#43]
Hi,

I got this error after try to install:

`
No source for ruby-2.5.0 (revision 58466) provided with debase-ruby_core_source gem.`

More detailed:
https://gist.github.com/wellington1993/2c6608777b8b6cf7ef3f87c55d7bd55e

Any idea to help me?

**Comment by os97673** [comment]
I might be wrong but I do not see any official releases for ruby 2.5.0 thus debase-ruby_core_source doesn't provide sources for this.  If you build ruby 2.5.0 from source you may want to point to them (see ext/extconf.rb and --with-ruby-include).
