### ISSUE TITLE
ibf_load_iseq_complete in debase_internals not found

### ISSUE THREAD

**Issue by tiesel** [denofevil/debase#64]
Dear Team,
the call to ibf_load_iseq_complete is not found in debase_internals.so on fedora 28.
Source is debase_internals.c:647,
version is tag v0.2.3.beta2 if I get this right.
I can't find the definition in the code. Is there another library that should be linked?
Thanks in advance
Matthias

**Comment by ViugiNick** [comment]
@tiesel What ruby version do you use?

**Comment by tiesel** [comment]
It is ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by ViugiNick** [comment]
@tiesel https://github.com/os97673/debase-ruby_core_source/blob/882e9c632348cbde5e7d5d04edd70b9627f29397/lib/debase/ruby_core_source/ruby-2.5.1-p57/iseq.h#L160
It seems that the problem is in linking and building. Could you clarify whether you use rvm/rbenv or system ruby?

**Comment by tiesel** [comment]
It's plain system ruby, latest version.
ruby-2.5.1-93.fc28.x86_64 is the package name

**Comment by mpokrywka** [comment]
Commit "monkeypatch load_iseq for debugger to work along with bootsnap" will not work with system ruby, because symbol "ibf_load_iseq_complete" is not exported (I checked my system's /usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5 )

**Comment by tiesel** [comment]
So, finally I was able to solve the problem -- at least for me (Fedora 28, newest patches):
gem uninstall --user-install debase
selected debase-0.2.3.beta2
, so that debase-0.2.2 is the newest version. That obviously doesn't require ibf_load_iseq_complete.

**Comment by ViugiNick** [comment]
@tiesel @mpokrywka Looks like it can be fixed for the 2.5.2 version, are you OK with using it?

**Comment by openscript** [comment]
I ran in the same problem with `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]` as a system installation:

    /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /home/rdex/.gem/ruby/2.5.0/gems/debase-0.2.3.beta2/lib/debase_internals.so: undefined symbol: ibf_load_iseq_complete - /home/rdex/.gem/ruby/2.5.0/gems/debase-0.2.3.beta2/lib/debase_internals.so (LoadError)

Currently I don't have a solution for `debase-0.2.3.beta2` and `Ruby 2.5.3p105`.

**Comment by openscript** [comment]
I've switched to `asdf`. As already mentioned by @ViugiNick it works with a non-system ruby installation.

**Comment by tiesel** [comment]
@ViugiNick 
Sorry I come back so late: This is perfectly o.k. with me.
It was mainly a lack of ruby Gemfile / rubymine skills at my site and I am now able to compose a gems / versions collection and debug with it. So go ahead, if you didn't already.

**Comment by tiesel** [comment]
Under F29, using vanilla ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
this still persists. But fortunately, the solution still works:
gem uninstall --user-install debase
selected debase-0.2.3.beta2
, so that debase-0.2.2 is the newest version. Voila, debugging works again.

**Comment by ViugiNick** [comment]
@tiesel Did you try 0.2.3.beta5?

**Comment by tiesel** [comment]
Very nice!
The debugger works with debase:0.2.3.beta5 here on Fedora 29,
vanilla ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
Thanks a lot!
