### ISSUE TITLE
Deprecation warning: warning: $SAFE will become a normal global variable in Ruby 3.0

### ISSUE THREAD

**Issue by qortex** [denofevil/debase#86]
This warning shows up in the console when a variable needs to be evaluated in the `watch` panel (using vscode and `ruby-debug-ide`):
```
warning: $SAFE will become a normal global variable in Ruby 3.0
```

**Comment by ViugiNick** [comment]
@qortex Can't find $SAFE occurrences, maybe the problem is on the vscode plugin side

**Comment by qortex** [comment]
Ok thanks, will look into it!

**Comment by dkallipo** [comment]
@qortex is there any solution to this problem? Why was the issue closed. Thanks

**Comment by qortex** [comment]
Don't know, didn't look into it more than that.
It would be interesting to look up the root cause and know where it comes from, from debase or the vscode plugin.

**Comment by dkallipo** [comment]
I found the root cause: it's because of vs code's evaluation of global variables during debugging. One way to solve this is by hiding the 'variables' sub-panel on the side-bar.

**Comment by qortex** [comment]
Which project is it located in? We could work towards a fix PR.

**Comment by denofevil** [comment]
I think it might be handled on ruby-debug/ruby-debug-ide side, https://github.com/ruby-debug/ruby-debug-ide/blob/master/lib/ruby-debug-ide/commands/variables.rb#L41 //cc @ViugiNick

**Comment by dkallipo** [comment]
> Which project is it located in? We could work towards a fix PR.

What I described was actually just a workaround to get rid of the annoying warning by just changing the VS code GUI settings. FYI, I resorted to downgrading to Ruby 2.6 because I was experiencing inconsistent and strange behavior by the VS code debugger.
