### ISSUE TITLE
Hash variables as string?

### ISSUE THREAD

**Issue by qortex** [denofevil/debase#87]
It looks like variables are stringified (`to_s`?) to be shown in the Watch panel (using visual studio code).

Is there a way to have them displayed as a navigable tree when it's a hash? (as in the variables pane)

**Comment by ViugiNick** [comment]
@qortex Current implementation of ruby-debug-ide/debase gems allows to implement such representation. So it's better to create an issue in vscode plugin repo.

Thats how it looks in RubyMine:
![image](https://user-images.githubusercontent.com/6137315/79153231-2f676500-7dd6-11ea-905c-7ebce8d7b60b.png)

**Comment by qortex** [comment]
Thanks, I'll do that!
