### ISSUE TITLE
Error: cannot load such file -- debugger/ruby_core_source 

### ISSUE THREAD

**Issue by JohnBat26** [denofevil/debase#9]
Hi.
I get next error when install debase:
gem install debase

```
Building native extensions.  This could take a while...
ERROR:  Error installing debase:
        ERROR: Failed to build gem native extension.

    /home/johnbat26/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/johnbat26/.rvm/rubies/ruby-2.0.0-p247/bin/ruby
/home/johnbat26/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require': cannot load such file -- debugger/ruby_core_source (LoadError)
        from /home/johnbat26/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:51:in `require'
        from extconf.rb:16:in `<main>'
Gem files will remain installed in /home/johnbat26/.rvm/gems/ruby-2.0.0-p247@wc/gems/debase-0.0.7 for inspection.
Results logged to /home/johnbat26/.rvm/gems/ruby-2.0.0-p247@wc/gems/debase-0.0.7/ext/gem_make.out
```

I try to install gem install debugger-ruby_core_source, but this don't help :(

**Comment by moeffju** [comment]
I’m getting this error suddenly in a previously working installation without touching the Gemfile or debase version. Installing `debase-ruby_core_source` (0.7.5) works, but the installation of `debase` itself fails:

```
/Users/moeffju/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- debase/ruby_core_source (LoadError)
	from /Users/moeffju/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from extconf.rb:28:in `<main>'

extconf failed, exit code 1
```

**Comment by atefth** [comment]
I have no debug gems install (ruby-debug-ide)

![screen shot 2016-03-22 at 2 58 51 pm](https://cloud.githubusercontent.com/assets/2331530/13944241/b19bc5ae-f03e-11e5-98a7-d62d6b7b95aa.png)
![screen shot 2016-03-22 at 2 59 05 pm](https://cloud.githubusercontent.com/assets/2331530/13944242/b1a0e6ce-f03e-11e5-98f9-c7f877614e10.png)

Here is my mkmf.log:

[mkmf.txt](https://github.com/denofevil/debase/files/183636/mkmf.txt)

What could be causing this build issue?

**Comment by Eric-Guo** [comment]
@atefth because you are using `2.4.0-dev`, which probably the ruby master version, so won't include in ruby_core_source.

So do not using ruby 2.4.0, using 2.3.0 instead.

**Comment by atefth** [comment]
Thanks a bunch @Eric-Guo! :+1:

**Comment by denofevil** [comment]
@atefth alternatively you can specify --with-ruby-include= command line argument and provide 2.4.0 sources location

**Comment by atefth** [comment]
@denofevil I tried doing that but the thing is I use rbenv for managing my ruby versions and I tried using the ruby include parameter while installing the gem; It was throwing an invalid parameter parse error or something... I guess I am not really sure where rbenv places the ruby source.. oiamanoob!
